
pull_request_rules:
  - name: automatically merge scala-steward's PRs
    conditions:
      - author=scala-steward
      - body~=labels:.*semver-patch.*
      - status-success=Build and Test (ubuntu-latest, 2.13.3, adopt@1.8)
      - status-success=Build and Test (ubuntu-latest, 2.13.3, adopt@1.11)
      - status-success=Build and Test (ubuntu-latest, 2.13.3, adopt@1.15)
      - status-success=Build and Test (ubuntu-latest, 2.12.12, adopt@1.8)
      - status-success=Build and Test (ubuntu-latest, 2.12.12, adopt@1.11)
      - status-success=Build and Test (ubuntu-latest, 2.12.12, adopt@1.15)
      - status-success=Build website (ubuntu-latest, 2.12.12, adopt@1.8)
      - status-success=Build docs (ubuntu-latest, 2.12.12, adopt@1.8)
    actions:
      merge:
        method: merge
